spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-calss-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.59.81:3306/blogs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
#配置评论的统一头像
comment.avatar: /images/avatar.png
server:
  port: 8080

#配置文件的mybatis的配置设置，注解方式可以不用
mybatis:
  mapper-locations: classpath:mapper/*.xml